os:
- linux
services:
- docker
language: node_js
node_js:
- 10.15.0
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
env:
  global:
  - NODE_VERSION=10.15.0
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - JHI_DISABLE_WEBPACK_LOGS=true
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: IPD/3xgibWjKI5hOlfMzQfrkcmhlF/dOqHP8nCq2QcHzmJwWYzTkJ0YLHW/bmfYmWW9J3C6T2gMRuCKdvlzYk6TsF3dfhoBdLeHK+LRzASZ92xgydMCgM39wyx7qDL6FbfMCy5kkneUd7hIrRHmPB07VjboTFxJBSKvgyf7rf5d/9tk6ScTd0+/0pxfuIbseIUZohzeWMIVxaBNACu+66FRdPQUIJHvucwS+TJKpbUX7uQa24GDC+2SkhuMeJt2fsArholc9xsMsOzhzRDaGZ7PfXAawuj0uUtkIzQ5UHAI+Kr4DqmYIzuGnirQw/BumXxCQIM9GCN7bbFQiN7EdgtEZuKLQeZ7+p/a3OsT2unBeQ3RcoJhXX56+laEo/0eqwbVY2Xq1ieFwxP9HzZ4p0g5hbpZFGqdVB0MXhe6iNmT8+eRMg43WFM/P0mEOWgf/OqYwIuCSouA8GyMWcF5KywPF9c4Fknj4py9Rd45aPib2hGfRprBOW8QK9N0y4k/wXVXxa07q5DwSgCC3IthsCWeHCuYz9qTVoUxwQ8VZnUonM/2lChn4PKuC0uOJP4XpaJyqFK52TAFLW2RmF62BCyEoiKCA598v9ZJsu4BbNqRtijy5PMGomskjJ2urVG5SutnewFs0I296QYmHOL+2b4DUCyyPUOi6KlAXwzJNhcs=
  - secure: RR0CGlpdsxpQUiJTZxhzklv9HZtk2JdJIxOW/MB0f9KHPPKD26iOERr437N7x2lln4D8JvVOWOJA9vRQdYxpgsO+8SYUjNEJzw7BWmmyy1FdUIo6hTRi7k0W+gMrAx5mfCESjB84vqcGlwi7FdUfWz6KfDo3nUkVG6516HRToWxhndX/Wk9+VxDObi/dBBRP2iSQpALlHCbS6fAofHTCsyyfP1gBVoxMq+AZOr5d8vjONobHrQFr2xLNVSb1e4Gmoacco2sbE6N2qwWbjG63Wp/IeufAKtLeYTHX9gsDy4OUJOR7BkkLJnTCfMUuiV+3hla6vTTTrVokOiDxphVmyahNTHOdsdd8h5fHyJEGidjdWmda7lr2t+xGJAdU+RV1YsvgJqR3b1/Hg/UK8DrxOlb1jwjdO3dtn2ufBqT2v1oEAjEnf6JDUOC+rTc1okLiCWEBW4Puad0X4JXR9Zx3p2G7UP7F/vQLnGpPiJUmewRdf2QK0uYwB/WvQ8i5krhblXjitFI9xAvSwx6wk1XAUIBgttiPsvcbFzpEzDZVramEbVpUuiUvKWuedQ2LX9daskZZ6rffmqTvBjsIrGJD30NMhtVzkqVOJ/SPFKl6EbSCJuFyyH91/K9ybhQSA/I/qQDewl3gW9NXhaD3thgr8HWXUpzlDMjGuIr1EuhLHH8=
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- nvm install $NODE_VERSION
- npm install -g npm
- node -v
- npm -v
install:
- npm install
script:
- chmod +x mvnw
- "./mvnw clean test"
- "./mvnw com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run
  test-ci' -Dmaven.repo.local=$MAVEN_USER_HOME"
- "./mvnw package -DSkipTests=true -Pprod jib:dockerBuild"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=latest
- export IMAGE_NAME=udaysalian/gps_feb_2019
- docker tag gps_feb_2019 $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
