version: '2'
services:
    gps_netra-app:
        image: gps_netra
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gps_netra-mysql:3306/gps_netra?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gps_netra-mysql:
        extends:
            file: mysql.yml
            service: gps_netra-mysql
